# Generated by Django 5.2.5 on 2025-08-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_options_remove_staff_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='Unknown email', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
