# Generated by Django 5.2.5 on 2025-08-25 12:22

import api.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_notes_item_purchase_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staffitemassignment',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffitemassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffitemassignment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffitemassignment',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffitemassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name must be unique', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Item name (letters, numbers, spaces, and hyphens only)', max_length=200, validators=[api.validators.validate_item_name]),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price must be greater than 0', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique serial number', max_length=200, null=True, unique=True, validators=[api.validators.validate_serial_number]),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag_number',
            field=models.CharField(blank=True, help_text='Unique tag number', max_length=200, null=True, unique=True, validators=[api.validators.validate_tag_number]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=100, validators=[api.validators.validate_department_name]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(help_text='Email must be unique', max_length=254, unique=True, validators=[api.validators.validate_email_domain]),
        ),
        migrations.AlterField(
            model_name='staffitemassignment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.item'),
        ),
        migrations.AlterField(
            model_name='staffitemassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Supplier name must be unique', max_length=200, unique=True, validators=[api.validators.validate_supplier_name]),
        ),
        migrations.AlterUniqueTogether(
            name='staffitemassignment',
            unique_together={('staff', 'item')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='api_item_name_733099_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['serial_number'], name='api_item_serial__aa6ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tag_number'], name='api_item_tag_num_3d8dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['email'], name='api_staff_email_67a89a_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department'], name='api_staff_departm_c57d69_idx'),
        ),
        migrations.AddIndex(
            model_name='staffitemassignment',
            index=models.Index(fields=['assigned_date'], name='api_staffit_assigne_7ab20b_idx'),
        ),
        migrations.AddIndex(
            model_name='staffitemassignment',
            index=models.Index(fields=['staff', 'assigned_date'], name='api_staffit_staff_i_89dad7_idx'),
        ),
    ]
